import { MESSAGEPACK_CHANNELS } from '../messagepack/binary-ipc'

// IPC Channel Constants

export const IPC = {
  // App
  APP_HOMEDIR: 'app:homedir',
  APP_GLOBAL_MEMORY_HOME: 'app:global-memory-home',

  // API events
  API_QUOTA_UPDATE: 'api:quota-update',
  API_ACCOUNT_RATE_LIMITED: 'api:account-rate-limited',

  // File System
  FS_SELECT_FILE: 'fs:select-file',
  FS_SELECT_SAVE_FILE: 'fs:select-save-file',
  FS_READ_DOCUMENT: 'fs:read-document',
  FS_READ_FILE: 'fs:read-file',
  FS_READ_TEXT_FILE_LINES: 'fs:read-text-file-lines',
  FS_STAT_PATH: 'fs:stat-path',
  FS_WRITE_FILE: 'fs:write-file',
  FS_LIST_DIR: 'fs:list-dir',
  FS_MKDIR: 'fs:mkdir',
  FS_DEFAULT_CHAT_WORKING_FOLDER: 'fs:default-chat-working-folder',
  FS_DELETE: 'fs:delete',
  FS_MOVE: 'fs:move',
  FS_SELECT_FOLDER: 'fs:select-folder',
  FS_GLOB: 'fs:glob',
  FS_GREP: 'fs:grep',

  // File Watching
  FS_WATCH_FILE: 'fs:watch-file',
  FS_UNWATCH_FILE: 'fs:unwatch-file',
  FS_FILE_CHANGED: 'fs:file-changed',
  FS_WATCH_DIR: 'fs:watch-dir',
  FS_UNWATCH_DIR: 'fs:unwatch-dir',
  FS_DIR_CHANGED: 'fs:dir-changed',
  FS_READ_FILE_BINARY: 'fs:read-file-binary',
  FS_WRITE_FILE_BINARY: 'fs:write-file-binary',
  FS_IMPORT_PROFILE_AVATAR: 'fs:import-profile-avatar',

  // Shell
  SHELL_EXEC: 'shell:exec',
  SHELL_ABORT: 'shell:abort',
  SHELL_STARTED: 'shell:started',
  SHELL_OUTPUT: 'shell:output',
  SHELL_OPEN_PATH: 'shell:openPath',
  SHELL_SHOW_ITEM_IN_FOLDER: 'shell:showItemInFolder',
  SHELL_TRASH_PATH: 'shell:trashPath',
  SHELL_OPEN_WITH_APP: 'shell:openWithApp',
  SHELL_OPEN_EXTERNAL: 'shell:openExternal',

  // Local Terminal
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_INPUT: 'terminal:input',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  TERMINAL_GET: 'terminal:get',
  TERMINAL_LIST: 'terminal:list',
  TERMINAL_CREATED: 'terminal:created',
  TERMINAL_OUTPUT: 'terminal:output',
  TERMINAL_EXIT: 'terminal:exit',

  // Agent Changes
  AGENT_CHANGES_LIST_SESSION: 'agent:changes:list-session',
  AGENT_CHANGES_DIFF_CONTENT: 'agent:changes:diff-content',
  AGENT_CHANGES_UNDO_RUN: 'agent:changes:undo-run',
  AGENT_CHANGES_UNDO_FILE: 'agent:changes:undo-file',

  // Sub-Agent History
  SUB_AGENT_HISTORY_INDEX: 'agent:sub-agent-history:index',
  SUB_AGENT_HISTORY_LIST: 'agent:sub-agent-history:list',
  SUB_AGENT_HISTORY_APPLY: 'agent:sub-agent-history:apply',
  SUB_AGENT_HISTORY_REPLACE: 'agent:sub-agent-history:replace',
  SUB_AGENT_HISTORY_MIGRATION_STATUS: 'agent:sub-agent-history:migration-status',
  SUB_AGENT_HISTORY_MIGRATION_MARK: 'agent:sub-agent-history:migration-mark',

  // TS/WASM CodeGraph service
  CODEGRAPH_REQUEST: 'codegraph:request',
  CODEGRAPH_STATUS: 'codegraph:status',
  CODEGRAPH_STOP: 'codegraph:stop',
  CODEGRAPH_RECYCLE: 'codegraph:recycle',
  CODEGRAPH_INDEX_PROGRESS: 'codegraph:index-progress',

  // Memory Automation
  MEMORY_AUTOMATION_LIST: 'memory-automation:list',
  MEMORY_AUTOMATION_RECORD: 'memory-automation:record',
  MEMORY_AUTOMATION_UNDO: 'memory-automation:undo',
  MEMORY_AUTOMATION_RUN_SESSION: 'memory-automation:run-session',
  MEMORY_AUTOMATION_RUN_ROLLUP: 'memory-automation:run-rollup',
  MEMORY_PIPELINE_RUN: 'memory-pipeline:run',
  MEMORY_PIPELINE_LIST_ROOTS: 'memory-pipeline:list-roots',
  MEMORY_PIPELINE_LIST_JOBS: 'memory-pipeline:list-jobs',
  MEMORY_PIPELINE_CLEAR_ROOT: 'memory-pipeline:clear-root',
  MEMORY_RECORD_CITATION_USAGE: 'memory:record-citation-usage',

  // Process Management
  PROCESS_SPAWN: 'process:spawn',
  PROCESS_KILL: 'process:kill',
  PROCESS_WRITE: 'process:write',
  PROCESS_STATUS: 'process:status',
  PROCESS_LIST: 'process:list',
  PROCESS_OUTPUT: 'process:output',

  // Settings
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_CHANGED: 'settings:changed',
  WEB_SEARCH_SECRET_STATUS: 'web:search-secret-status',
  WEB_SEARCH_SECRET_SET: 'web:search-secret-set',
  WEB_SEARCH_SECRET_DELETE: 'web:search-secret-delete',

  // Extensions
  EXTENSION_LIST: 'extension:list',
  EXTENSION_INSTALL_FROM_FOLDER: 'extension:install-from-folder',
  EXTENSION_UPDATE: 'extension:update',
  EXTENSION_REMOVE: 'extension:remove',
  EXTENSION_OPEN_FOLDER: 'extension:open-folder',
  EXTENSION_READ_ASSET: 'extension:read-asset',
  EXTENSION_STORAGE_GET: 'extension:storage-get',
  EXTENSION_STORAGE_SET: 'extension:storage-set',
  EXTENSION_STORAGE_DELETE: 'extension:storage-delete',

  // SOUL Market
  SOULS_BUILTIN_LIST: 'souls:builtin-list',
  SOULS_MARKET_LIST: 'souls:market-list',
  SOULS_CATEGORIES: 'souls:categories',
  SOULS_DOWNLOAD_REMOTE: 'souls:download-remote',
  SOULS_GET_TARGET_PATHS: 'souls:get-target-paths',
  SOULS_INSTALL: 'souls:install',

  // Migration
  MIGRATION_PREVIEW: 'migration:preview',
  MIGRATION_APPLY: 'migration:apply',
  MIGRATION_BUSINESS_HANDOVER_STATUS: 'migration:business-handover-status',
  MIGRATION_BUSINESS_HANDOVER: 'migration:business-handover',

  // Sync
  SYNC_CONFIG_GET: 'sync:config:get',
  SYNC_CONFIG_SET: 'sync:config:set',
  SYNC_PROVIDERS_LIST: 'sync:providers:list',
  SYNC_CONNECTION_TEST: 'sync:connection:test',
  SYNC_STATUS: 'sync:status',
  SYNC_RUN: 'sync:run',
  SYNC_WORKSPACE_RUN: 'sync:workspace-run',
  SYNC_CONFLICTS_RESOLVE: 'sync:conflicts:resolve',
  SYNC_STATUS_CHANGED: 'sync:status-changed',
  SYNC_RUN_PROGRESS: 'sync:run-progress',
  SYNC_CONFLICT_FOUND: 'sync:conflict-found',
  SYNC_RUN_FINISHED: 'sync:run-finished',

  // Plugins
  PLUGIN_LIST_PROVIDERS: 'plugin:list-providers',
  PLUGIN_LIST: 'plugin:list',
  PLUGIN_ADD: 'plugin:add',
  PLUGIN_UPDATE: 'plugin:update',
  PLUGIN_REMOVE: 'plugin:remove',
  PLUGIN_START: 'plugin:start',
  PLUGIN_STOP: 'plugin:stop',
  PLUGIN_STATUS: 'plugin:status',
  PLUGIN_EXEC: 'plugin:exec',
  PLUGIN_SESSIONS_LIST: 'plugin:sessions:list',
  PLUGIN_SESSIONS_LIST_ALL: 'plugin:sessions:list-all',
  PLUGIN_SESSIONS_MESSAGES: 'plugin:sessions:messages',
  PLUGIN_SESSIONS_CREATE: 'plugin:sessions:create',
  PLUGIN_SESSIONS_CLEAR: 'plugin:sessions:clear',
  PLUGIN_SESSIONS_DELETE: 'plugin:sessions:delete',
  PLUGIN_SESSIONS_RENAME: 'plugin:sessions:rename',
  PLUGIN_INCOMING_MESSAGE: 'plugin:incoming-message',
  PLUGIN_SESSION_TASK: 'plugin:session-task',
  PLUGIN_SESSION_TASK_ACK: 'plugin:session-task:ack',
  PLUGIN_SESSIONS_FIND_BY_CHAT: 'plugin:sessions:find-by-chat',
  PLUGIN_STREAM_START: 'plugin:stream:start',
  PLUGIN_STREAM_UPDATE: 'plugin:stream:update',
  PLUGIN_STREAM_APPEND: 'plugin:stream:append',
  PLUGIN_STREAM_FINISH: 'plugin:stream:finish',

  // Weixin-specific
  PLUGIN_WEIXIN_LOGIN_START: 'plugin:weixin:login-start',
  PLUGIN_WEIXIN_LOGIN_WAIT: 'plugin:weixin:login-wait',
  PLUGIN_WEIXIN_SEND_IMAGE: 'plugin:weixin:send-image',
  PLUGIN_WEIXIN_SEND_FILE: 'plugin:weixin:send-file',

  // Feishu-specific
  PLUGIN_FEISHU_SEND_IMAGE: 'plugin:feishu:send-image',
  PLUGIN_FEISHU_SEND_FILE: 'plugin:feishu:send-file',
  PLUGIN_FEISHU_SEND_MENTION: 'plugin:feishu:send-mention',
  PLUGIN_FEISHU_LIST_MEMBERS: 'plugin:feishu:list-members',
  PLUGIN_FEISHU_SEND_URGENT: 'plugin:feishu:send-urgent',
  PLUGIN_FEISHU_DOWNLOAD_RESOURCE: 'plugin:feishu:download-resource',
  PLUGIN_FEISHU_BITABLE_LIST_APPS: 'plugin:feishu:bitable:list-apps',
  PLUGIN_FEISHU_BITABLE_LIST_TABLES: 'plugin:feishu:bitable:list-tables',
  PLUGIN_FEISHU_BITABLE_LIST_FIELDS: 'plugin:feishu:bitable:list-fields',
  PLUGIN_FEISHU_BITABLE_GET_RECORDS: 'plugin:feishu:bitable:get-records',
  PLUGIN_FEISHU_BITABLE_CREATE_RECORDS: 'plugin:feishu:bitable:create-records',
  PLUGIN_FEISHU_BITABLE_UPDATE_RECORDS: 'plugin:feishu:bitable:update-records',
  PLUGIN_FEISHU_BITABLE_DELETE_RECORDS: 'plugin:feishu:bitable:delete-records',

  // MCP
  MCP_LIST: 'mcp:list',
  MCP_ADD: 'mcp:add',
  MCP_UPDATE: 'mcp:update',
  MCP_REMOVE: 'mcp:remove',
  MCP_CONNECT: 'mcp:connect',
  MCP_DISCONNECT: 'mcp:disconnect',
  MCP_STATUS: 'mcp:status',
  MCP_SERVER_INFO: 'mcp:server-info',
  MCP_ALL_SERVERS_INFO: 'mcp:all-servers-info',
  MCP_LIST_TOOLS: 'mcp:list-tools',
  MCP_CALL_TOOL: 'mcp:call-tool',
  MCP_LIST_RESOURCES: 'mcp:list-resources',
  MCP_READ_RESOURCE: 'mcp:read-resource',
  MCP_LIST_PROMPTS: 'mcp:list-prompts',
  MCP_GET_PROMPT: 'mcp:get-prompt',
  MCP_REFRESH_CAPABILITIES: 'mcp:refresh-capabilities',

  // Cron Scheduler (v2)
  CRON_ADD: 'cron:add',
  CRON_UPDATE: 'cron:update',
  CRON_REMOVE: 'cron:remove',
  CRON_DELETE: 'cron:delete',
  CRON_LIST: 'cron:list',
  CRON_TOGGLE: 'cron:toggle',
  CRON_RUN_NOW: 'cron:run-now',
  CRON_RUNS: 'cron:runs',
  CRON_RUN_CREATE: 'cron:run:create',
  CRON_RUN_UPDATE: 'cron:run:update',
  CRON_RUN_DETAIL: 'cron:run-detail',
  CRON_DELIVERY_RECONCILE: 'cron:delivery-reconcile',
  CRON_DELIVERY_RETRY: 'cron:delivery-retry',
  CRON_RUN_MESSAGES_REPLACE: 'cron:run-messages:replace',
  CRON_RUN_LOG_APPEND: 'cron:run-log:append',
  CRON_FIRED: 'cron:fired',
  CRON_JOB_REMOVED: 'cron:job-removed',
  CRON_RUN_FINISHED: 'cron:run-finished',
  CRON_SESSION_DELIVERED: 'cron:session-delivered',
  CRON_ABORT_RUN: 'cron:abort-run',
  CRON_RUN_STARTED: 'cron:run-started',
  CRON_RUN_PROGRESS: 'cron:run-progress',
  CRON_RUN_LOG_APPENDED: 'cron:run-log-appended',

  // Notify
  NOTIFY_DESKTOP: 'notify:desktop',
  NOTIFY_SESSION: 'notify:session',

  // App Updates
  UPDATE_AVAILABLE: 'update:available',

  GIT_GET_HEAD: 'git:get-head',
  GIT_GET_RANGE_COMMITS: 'git:get-range-commits',
  GIT_GET_CHANGED_FILES: 'git:get-changed-files',
  GIT_GET_STATUS: 'git:get-status',
  GIT_GET_LINE_SUMMARY: 'git:get-line-summary',
  GIT_SCAN_REPOSITORIES: 'git:scan-repositories',
  GIT_GET_REPO_SUMMARY: 'git:get-repo-summary',
  GIT_GET_STATUS_DETAILED: 'git:get-status-detailed',
  GIT_GET_FILE_DIFF: 'git:get-file-diff',
  GIT_GET_FILE_DIFF_AT_COMMIT: 'git:get-file-diff-at-commit',
  GIT_GET_FILE_CONTENT_AT_REF: 'git:get-file-content-at-ref',
  GIT_GET_STAGED_DIFF_BUNDLE: 'git:get-staged-diff-bundle',
  GIT_GET_COMMIT_HISTORY: 'git:get-commit-history',
  GIT_LIST_BRANCHES: 'git:list-branches',
  GIT_FETCH: 'git:fetch',
  GIT_PULL_REBASE: 'git:pull-rebase',
  GIT_PUSH: 'git:push',
  GIT_GET_FILE_HISTORY: 'git:get-file-history',
  GIT_CREATE_BRANCH: 'git:create-branch',
  GIT_CHECKOUT_BRANCH: 'git:checkout-branch',
  GIT_MERGE_BRANCH: 'git:merge-branch',
  GIT_REBASE_BRANCH: 'git:rebase-branch',
  GIT_DELETE_LOCAL_BRANCH: 'git:delete-local-branch',
  GIT_DELETE_REMOTE_BRANCH: 'git:delete-remote-branch',
  GIT_RENAME_BRANCH: 'git:rename-branch',
  GIT_STAGE_FILES: 'git:stage-files',
  GIT_UNSTAGE_FILES: 'git:unstage-files',
  GIT_STAGE_ALL: 'git:stage-all',
  GIT_UNSTAGE_ALL: 'git:unstage-all',
  GIT_DISCARD_FILES: 'git:discard-files',
  GIT_COMMIT: 'git:commit',
  UPDATE_CHECK: 'update:check',
  UPDATE_DOWNLOAD: 'update:download',
  UPDATE_STATUS: 'update:status',
  UPDATE_INSTALL: 'update:install',
  UPDATE_DOWNLOAD_PROGRESS: 'update:download-progress',
  UPDATE_DOWNLOADED: 'update:downloaded',
  UPDATE_ERROR: 'update:error',
  CHAT_SESSION_UPDATED: 'chat:session-updated',
  CHAT_SESSION_DELETED: 'chat:session-deleted',
  CHAT_PROJECT_UPDATED: 'chat:project-updated',
  CHAT_PROJECT_DELETED: 'chat:project-deleted',

  // Skills
  SKILLS_LIST: 'skills:list',
  SKILLS_LOAD: 'skills:load',
  SKILLS_ENSURE_BUILTIN: 'skills:ensure-builtin',
  SKILLS_DELETE: 'skills:delete',
  SKILLS_OPEN_FOLDER: 'skills:open-folder',
  SKILLS_ADD_FROM_FOLDER: 'skills:add-from-folder',
  SKILLS_READ: 'skills:read',
  SKILLS_LIST_FILES: 'skills:list-files',
  SKILLS_SAVE: 'skills:save',
  SKILLS_SCAN: 'skills:scan',
  SKILLS_MARKET_LIST: 'skills:market-list',
  SKILLS_DOWNLOAD_REMOTE: 'skills:download-remote',
  SKILLS_CLEANUP_TEMP: 'skills:cleanup-temp',

  // Prompts
  PROMPTS_LIST: 'prompts:list',
  PROMPTS_LOAD: 'prompts:load',

  // Agents
  AGENTS_MANAGE_LIST: 'agents:manage-list',
  AGENTS_MANAGE_READ: 'agents:manage-read',
  AGENTS_MANAGE_SAVE: 'agents:manage-save',

  // Commands
  COMMANDS_LIST: 'commands:list',
  COMMANDS_LOAD: 'commands:load',
  COMMANDS_MANAGE_LIST: 'commands:manage-list',
  COMMANDS_MANAGE_READ: 'commands:manage-read',
  COMMANDS_MANAGE_CREATE: 'commands:manage-create',
  COMMANDS_MANAGE_SAVE: 'commands:manage-save',

  // Clipboard
  CLIPBOARD_WRITE_IMAGE: 'clipboard:write-image',
  WINDOW_CAPTURE_REGION: 'window:capture-region',
  SSH_WINDOW_OPEN: 'ssh-window:open',
  SESSION_WINDOW_OPEN: 'session-window:open',
  SESSION_WINDOW_FOCUS_IF_OPEN: 'session-window:focus-if-open',
  SESSION_RUNTIME_SYNC: 'session-runtime:sync',
  SESSION_CONTROL_SYNC: 'session-control:sync',
  AGENT_RUNTIME_SYNC: 'agent-runtime:sync',

  // Images
  IMAGE_PERSIST_GENERATED: 'image:persist-generated',
  IMAGE_CREATE_GIF_FROM_GRID: 'image:create-gif-from-grid',

  // Desktop Control
  DESKTOP_SCREENSHOT_CAPTURE: 'desktop:screenshot:capture',
  DESKTOP_INPUT_CLICK: 'desktop:input:click',
  DESKTOP_INPUT_TYPE: 'desktop:input:type',
  DESKTOP_INPUT_SCROLL: 'desktop:input:scroll',
  DESKTOP_INPUT_STATUS: 'desktop:input:status',

  // Web Search
  WEB_SEARCH: 'web:search',
  WEB_FETCH: 'web:fetch',
  WEB_SEARCH_CONFIG: 'web:search-config',
  WEB_SEARCH_PROVIDERS: 'web:search-providers',

  // Built-in Browser
  BROWSER_CLEAR_COOKIES: 'browser:clear-cookies',
  BROWSER_EXPORT_COOKIES: 'browser:export-cookies',
  BROWSER_EMULATION_STATUS: 'browser:emulation-status',
  BROWSER_COOKIE_PROFILES: 'browser:cookie-profiles',
  BROWSER_IMPORT_COOKIES: 'browser:import-cookies',
  BROWSER_REGISTER_TAB: 'browser:register-tab',
  BROWSER_NAVIGATE: 'browser:navigate',
  BROWSER_NAVIGATE_GUEST: 'browser:navigate-guest',
  BROWSER_EXECUTE_SCRIPT: 'browser:execute-script',
  BROWSER_CAPTURE_PAGE: 'browser:capture-page',
  BROWSER_TAKE_CONTROL: 'browser:take-control',
  BROWSER_TAKE_RUN_CONTROL: 'browser:take-run-control',
  BROWSER_TAKE_GUEST_RUN_CONTROL: 'browser:take-guest-run-control',
  BROWSER_UNREGISTER_TAB: 'browser:unregister-tab',
  BROWSER_VIEW_CREATE: 'browser:view-create',
  BROWSER_VIEW_STATUS: 'browser:view-status',
  BROWSER_VIEW_EVENT: 'browser:view-event',
  BROWSER_VIEW_SET_BOUNDS: 'browser:view-set-bounds',
  BROWSER_VIEW_NAVIGATE: 'browser:view-navigate',
  BROWSER_VIEW_DESTROY: 'browser:view-destroy',

  // AI Coding
  AI_CODING_CONFIGS_LIST: 'ai-coding:configs-list',
  AI_CODING_CONFIGS_SAVE: 'ai-coding:configs-save',
  AI_CODING_CONFIGS_DELETE: 'ai-coding:configs-delete',
  AI_CODING_TERMINAL_LAUNCH: 'ai-coding:terminal-launch',

  // Credentials
  CREDENTIALS_VAULT_STATUS: 'credentials:vault-status',
  CREDENTIALS_STORE: 'credentials:store',
  CREDENTIALS_LIST: 'credentials:list',
  CREDENTIALS_DELETE: 'credentials:delete',
  CREDENTIALS_LIST_TEMPLATES: 'credentials:list-templates',
  CREDENTIALS_ENABLE_TEMPLATE: 'credentials:enable-template',
  CREDENTIALS_RECORD_VERIFICATION: 'credentials:record-verification',
  CREDENTIALS_FILL_PASSWORD: 'credentials:fill-password',
  CREDENTIALS_UPDATE: 'credentials:update',

  // OAuth
  OAUTH_START: 'oauth:start',
  OAUTH_STOP: 'oauth:stop',
  OAUTH_CALLBACK: 'oauth:callback',

  // Remote Control
  REMOTE_CONNECTION_LIST: 'remote:connection:list',
  REMOTE_CONNECTION_CREATE: 'remote:connection:create',
  REMOTE_CONNECTION_UPDATE: 'remote:connection:update',
  REMOTE_CONNECTION_TEST: 'remote:connection:test',
  REMOTE_CONNECTION_DELETE: 'remote:connection:delete',
  REMOTE_SESSION_LIST: 'remote:session:list',
  REMOTE_SESSION_CLAIM_CREDENTIAL: 'remote:session:claim-credential',
  REMOTE_CONNECT: 'remote:connect',
  REMOTE_DISCONNECT: 'remote:disconnect',
  REMOTE_RDP_DETECT: 'remote:rdp:detect',
  REMOTE_VNC_DETECT: 'remote:vnc:detect',
  REMOTE_INPUT_SET_SESSION: 'remote:input:set-session',
  REMOTE_INPUT_DISPATCH: 'remote:input:dispatch',
  REMOTE_ACCOUNT_INVOKE: 'remote:account:invoke',
  REMOTE_CAPTURE_PERMISSION: 'remote:capture:permission',
  REMOTE_CAPTURE_SOURCES: 'remote:capture:sources',

  // SSH Management
  SSH_GROUP_LIST: 'ssh:group:list',
  SSH_GROUP_CREATE: 'ssh:group:create',
  SSH_GROUP_UPDATE: 'ssh:group:update',
  SSH_GROUP_DELETE: 'ssh:group:delete',
  SSH_CONNECTION_LIST: 'ssh:connection:list',
  SSH_CONNECTION_CREATE: 'ssh:connection:create',
  SSH_CONNECTION_UPDATE: 'ssh:connection:update',
  SSH_CONNECTION_DELETE: 'ssh:connection:delete',
  SSH_CONNECTION_TEST: 'ssh:connection:test',

  // SSH Terminal Sessions
  SSH_CONNECT: 'ssh:connect',
  SSH_DISCONNECT: 'ssh:disconnect',
  SSH_DATA: 'ssh:data',
  SSH_OUTPUT: 'ssh:output',
  SSH_OUTPUT_BUFFER: 'ssh:output:buffer',
  SSH_RESIZE: 'ssh:resize',
  SSH_STATUS: 'ssh:status',
  SSH_SESSION_LIST: 'ssh:session:list',
  SSH_WORKSPACE_ACTIVITY: 'ssh:workspace-activity',
  SSH_DIAGNOSTICS_LIST: 'ssh:diagnostics:list',

  // SSH File Operations (SFTP)
  SSH_FS_READ_FILE: 'ssh:fs:read-file',
  SSH_FS_READ_TEXT_FILE_LINES: 'ssh:fs:read-text-file-lines',
  SSH_FS_STAT_PATH: 'ssh:fs:stat-path',
  SSH_FS_WRITE_FILE: 'ssh:fs:write-file',
  SSH_FS_READ_FILE_BINARY: 'ssh:fs:read-file-binary',
  SSH_FS_WRITE_FILE_BINARY: 'ssh:fs:write-file-binary',
  SSH_FS_LIST_DIR: 'ssh:fs:list-dir',
  SSH_FS_MKDIR: 'ssh:fs:mkdir',
  SSH_FS_DELETE: 'ssh:fs:delete',
  SSH_FS_MOVE: 'ssh:fs:move',
  SSH_FS_GLOB: 'ssh:fs:glob',
  SSH_FS_GREP: 'ssh:fs:grep',
  SSH_FS_HOME_DIR: 'ssh:fs:home-dir',
  SSH_FS_ZIP_DIR: 'ssh:fs:zip-dir',
  SSH_FS_DOWNLOAD: 'ssh:fs:download',
  SSH_FS_CONNECT: 'ssh:fs:connect',
  SSH_FS_DISCONNECT: 'ssh:fs:disconnect',
  SSH_FS_UPLOAD_START: 'ssh:fs:upload:start',
  SSH_FS_UPLOAD_CANCEL: 'ssh:fs:upload:cancel',
  SSH_FS_UPLOAD_ABORT: 'ssh:fs:upload:abort',
  SSH_FS_DOWNLOAD_ABORT: 'ssh:fs:download:abort',
  SSH_FS_REMOTE_COPY_ABORT: 'ssh:fs:remote-copy:abort',
  SSH_FS_UPLOAD_EVENTS: 'ssh:fs:upload:events',
  SSH_FS_TRANSFER_START: 'ssh:fs:transfer:start',
  SSH_FS_TRANSFER_CANCEL: 'ssh:fs:transfer:cancel',
  SSH_FS_TRANSFER_SCAN: 'ssh:fs:transfer:scan',
  SSH_FS_TRANSFER_EVENTS: 'ssh:fs:transfer:events',

  // SSH Auth
  SSH_AUTH_INSTALL_PUBLIC_KEY: 'ssh:auth:install-public-key',

  // SSH Import / Export
  SSH_EXPORT: 'ssh:export',
  SSH_IMPORT_PREVIEW: 'ssh:import:preview',
  SSH_IMPORT_APPLY: 'ssh:import:apply',

  // SSH Remote Exec
  SSH_EXEC: 'ssh:exec',

  // Contract-normalized legacy channels (auto-registered)
  AGENTS_LIST: 'agents:list',
  API_REQUEST: 'api:request',
  APP_SYSTEM_INFO: 'app:system-info',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  DESKTOP_FLOW_ACTIVITY: 'desktop-flow:activity',
  DESKTOP_FLOW_CANCEL: 'desktop-flow:cancel',
  DESKTOP_FLOW_DELETE: 'desktop-flow:delete',
  DESKTOP_FLOW_LIST: 'desktop-flow:list',
  DESKTOP_FLOW_REPLAY: 'desktop-flow:replay',
  DESKTOP_FLOW_RUNS_LIST: 'desktop-flow:runs-list',
  DESKTOP_FLOW_SAVE: 'desktop-flow:save',
  DESKTOP_FLOW_SYNC: 'desktop-flow:sync',
  DESKTOP_RECORDER_CURRENT: 'desktop-recorder:current',
  DESKTOP_RECORDER_START: 'desktop-recorder:start',
  DESKTOP_RECORDER_STATUS: 'desktop-recorder:status',
  DESKTOP_RECORDER_STOP: 'desktop-recorder:stop',
  DRAW_GRAPH_ASSET_SAVE: 'draw-graph:asset-save',
  DRAW_GRAPH_ASSETS_LIST: 'draw-graph:assets-list',
  DRAW_GRAPH_LOAD: 'draw-graph:load',
  DRAW_GRAPH_SAVE: 'draw-graph:save',
  FS_LIST_DESKTOP_DIRECTORIES: 'fs:list-desktop-directories',
  GOAL_CLEARED: 'goal:cleared',
  GOAL_CONTINUE_REQUESTED: 'goal:continue-requested',
  GOAL_EVENT_ADDED: 'goal:event-added',
  GOAL_RUN_STATE: 'goal:run-state',
  GOAL_UPDATED: 'goal:updated',
  HOOKS_EMIT: 'hooks:emit',
  HOOKS_HISTORY: 'hooks:history',
  HOOKS_LIST: 'hooks:list',
  HOOKS_REVOKE: 'hooks:revoke',
  HOOKS_TRUST: 'hooks:trust',
  IMAGE_GENERATE: 'image:generate',
  INPUT_DRAFT_DELETE: 'input-draft:delete',
  INPUT_DRAFT_FLUSH: 'input-draft:flush',
  INPUT_DRAFT_READ: 'input-draft:read',
  INPUT_DRAFT_WRITE: 'input-draft:write',
  DB_PENDING_SESSION_QUEUE_GET: 'db:pending-session-queue:get',
  DB_PENDING_SESSION_QUEUE_REPLACE: 'db:pending-session-queue:replace',
  MEDIA_STATUS: 'media:status',
  MEDIA_TASK_CANCEL: 'media:task-cancel',
  MEDIA_TASK_CREATE: 'media:task-create',
  MEDIA_TASK_DELETE: 'media:task-delete',
  MEDIA_TASKS_LIST: 'media:tasks-list',
  NOTIFY_SESSION_MESSAGE: 'notify:session-message',
  PET_WINDOW_CLOSE: 'pet-window:close',
  PET_WINDOW_IDLE_SECONDS: 'pet-window:idle-seconds',
  PET_WINDOW_OPEN: 'pet-window:open',
  PET_WINDOW_SET_FOCUSABLE: 'pet-window:set-focusable',
  PET_WINDOW_SET_IGNORE_MOUSE: 'pet-window:set-ignore-mouse',
  PET_CREATE: 'pet:create',
  PET_DATA_DIR: 'pet:data-dir',
  PET_EXP_ADD: 'pet:exp-add',
  PET_EXPORT_ANIYA_TEMPLATE: 'pet:export-aniya-template',
  PET_IMPORT_COMPANION_FOLDER: 'pet:import-companion-folder',
  PET_OPEN_STUDIO: 'pet:open-studio',
  PET_SAVE_GENERATED_SPRITE: 'pet:save-generated-sprite',
  PET_SYNC: 'pet:sync',
  PET_SYNC_EVENT: 'pet:sync-event',
  PET_TRANSCRIBE: 'pet:transcribe',
  PET_TTS: 'pet:tts',
  PET_TTS_CANCEL: 'pet:tts-cancel',
  PET_TTS_STREAM: 'pet:tts-stream',
  PET_TTS_STREAM_EVENT: 'pet:tts-stream-event',
  PET_UPDATE: 'pet:update',
  PROVIDER_FALLBACK_RESOLVE: 'provider:fallback:resolve',
  PROVIDER_HEALTH: 'provider:health',
  PROVIDER_HEALTH_RESET: 'provider:health:reset',
  PROVIDER_MIRROR_SNAPSHOT: 'provider:mirror-snapshot',
  SSH_CONFIG_CHANGED: 'ssh:config:changed',
  TS_RUNTIME_WORKSPACE_ACTIVITY: 'ts-runtime:workspace-activity',
  WIKI_EXPORT: 'wiki:export',
  WIKI_GENERATE: 'wiki:generate',
  WIKI_GET: 'wiki:get',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:isMaximized',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_MAXIMIZED: 'window:maximized',
  WINDOW_MINIMIZE: 'window:minimize',

  // Renderer-verified channels (strict typing)
  MEDIA_SETTINGS_UPDATE: 'media:settings-update',
  FS_SEARCH_FILES: 'fs:search-files',
  DRAW_GRAPH_LIST: 'draw-graph:list',
  RUNTIME_APPROVAL_REQUEST_MSGPACK: 'runtime:approval-request:msgpack',
  EXECUTION_RECORDS_LIST_MSGPACK: 'execution-records:list:msgpack',
  EXECUTION_ARTIFACTS_LIST_MSGPACK: 'execution-artifacts:list:msgpack',
  EXECUTION_ARTIFACTS_HIDE_MSGPACK: 'execution-artifacts:hide:msgpack',
  HOOKS_CANCEL: 'hooks:cancel',
  WINDOW_WORKSPACE_SET: 'window:workspace:set'
} as const

export type IPCChannel = (typeof IPC)[keyof typeof IPC]

const ipcChannelSet = new Set<string>([
  ...Object.values(IPC),
  ...MESSAGEPACK_CHANNELS,
  'image:download',
  'image:fetch-base64',
  'clipboard:write-image',
  'team-runtime:create',
  'team-runtime:delete',
  'team-runtime:message:append',
  'team-runtime:snapshot',
  'team-runtime:member:update',
  'team-runtime:manifest:update',
  'team-runtime:messages:consume'
])

/**
 * Returns whether a channel is registered in the shared IPC contract.
 * MessagePack transport channels are checked separately because their
 * registration is maintained in the binary IPC contract.
 */
export function isKnownIpcChannel(channel: string): channel is IPCChannel {
  return ipcChannelSet.has(channel)
}

/** A MessagePack transport is allowed only for an already registered base channel. */
export function isKnownIpcTransportChannel(channel: string): boolean {
  if (isKnownIpcChannel(channel)) return true
  if (!channel.endsWith(':msgpack')) return false
  const base = channel.slice(0, -':msgpack'.length)
  return !base.endsWith(':msgpack') && isKnownIpcChannel(base)
}
