// <auto-generated />
// Generated by scripts/generate-agent-runtime-contract.mjs. Do not edit manually.

internal static class AgentRuntimeContract
{
    public const int Version = 1;

    public const string InitializeRoute = "initialize";
    public const string PingRoute = "ping";
    public const string ShutdownRoute = "shutdown";
    public const string CapabilitiesCheckRoute = "capabilities/check";
    public const string RunRoute = "agent/run";
    public const string ActiveRunsRoute = "agent/active-runs";
    public const string RunStatusRoute = "agent/run-status";
    public const string RunSnapshotRoute = "agent/run-snapshot";
    public const string CancelRoute = "agent/cancel";
    public const string RequestStopRoute = "agent/request-stop";
    public const string AppendMessagesRoute = "agent/append-messages";
    public const string CompressContextRoute = "agent/compress-context";
    public const string DebugBodyReadRoute = "agent/debug-body-read";
    public const string ReverseResponseRoute = "agent/reverse-response";
    public const string ReverseCancelRoute = "agent/reverse-cancel";
    public const string SessionVisibilityRoute = "agent/session-visibility";

    public static readonly HashSet<string> Capabilities = new(StringComparer.Ordinal)
    {
        "agent.run",
        "desktop.input",
        "provider.openai-chat",
        "provider.openai-responses",
        "provider.openai-images",
        "provider.anthropic",
        "provider.gemini",
        "provider.vertex-ai",
        "agent.stream.msgpack",
        "sidecar.reverse.msgpack",
        "db.messages.msgpack",
        "tool.Task",
        "tool.Todo",
        "tool.Fs",
        "tool.Search",
        "tool.Skill",
        "tool.Widget",
        "tool.Goal",
        "tool.Memory",
        "tool.CodeCompatible",
        "tool.Notify",
        "tool.Cron",
        "tool.AskUser",
        "tool.Plan",
        "tool.Translation",
        "tool.Plugin",
        "tool.Team",
        "tool.ChannelPlugin",
        "tool.ImageGenerate",
        "tool.Desktop",
        "tool.Browser",
        "tool.Mcp",
        "tool.Extension",
        "tool.WebSearch",
        "tool.WebFetch",
    };
}
