// Generated by scripts/generate-agent-runtime-contract.mjs. Do not edit manually.

export const AGENT_RUNTIME_CONTRACT_VERSION = 1

export const AGENT_RUNTIME_ROUTES = {
  initialize: 'initialize',
  ping: 'ping',
  shutdown: 'shutdown',
  capabilitiesCheck: 'capabilities/check',
  run: 'agent/run',
  activeRuns: 'agent/active-runs',
  runStatus: 'agent/run-status',
  runSnapshot: 'agent/run-snapshot',
  cancel: 'agent/cancel',
  requestStop: 'agent/request-stop',
  appendMessages: 'agent/append-messages',
  compressContext: 'agent/compress-context',
  debugBodyRead: 'agent/debug-body-read',
  reverseResponse: 'agent/reverse-response',
  reverseCancel: 'agent/reverse-cancel',
  sessionVisibility: 'agent/session-visibility'
} as const

export type AgentRuntimeRoute = (typeof AGENT_RUNTIME_ROUTES)[keyof typeof AGENT_RUNTIME_ROUTES]

export const AGENT_RUNTIME_CAPABILITIES = [
  'agent.run',
  'desktop.input',
  'provider.openai-chat',
  'provider.openai-responses',
  'provider.openai-images',
  'provider.anthropic',
  'provider.gemini',
  'provider.vertex-ai',
  'agent.stream.msgpack',
  'sidecar.reverse.msgpack',
  'db.messages.msgpack',
  'tool.Task',
  'tool.Todo',
  'tool.Fs',
  'tool.Search',
  'tool.Skill',
  'tool.Widget',
  'tool.Goal',
  'tool.Memory',
  'tool.CodeCompatible',
  'tool.Notify',
  'tool.Cron',
  'tool.AskUser',
  'tool.Plan',
  'tool.Translation',
  'tool.Plugin',
  'tool.Team',
  'tool.ChannelPlugin',
  'tool.ImageGenerate',
  'tool.Desktop',
  'tool.Browser',
  'tool.Mcp',
  'tool.Extension',
  'tool.WebSearch',
  'tool.WebFetch'
] as const

export type AgentRuntimeCapability = (typeof AGENT_RUNTIME_CAPABILITIES)[number]
