import assert from 'node:assert/strict'
import fs from 'node:fs'
const tool = fs.readFileSync('src/renderer/src/lib/tools/canvas-tool.ts', 'utf8')
const registry = fs.readFileSync('src/renderer/src/lib/tools/index.ts', 'utf8')
const store = fs.readFileSync('src/renderer/src/stores/draw-graph-store.ts', 'utf8')
assert.match(tool, /name: 'CanvasOperation'/)
assert.match(tool, /requiresApproval: \(input\) => input.action !== 'inspect'/)
assert.match(registry, /updateCanvasToolRegistration/)
assert.match(registry, /advancedDrawEnabled/)
assert.match(registry, /unregisterCanvasTool/)
assert.doesNotMatch(tool, /draw-graph:save/)
assert.match(tool, /useDrawGraphStore/)
assert.match(store, /changes:/)
assert.match(store, /source: 'assistant'/)
assert.match(store, /await ipcClient\.invoke\('draw-graph:save', next\)/)
console.log('Draw canvas assistant verification passed')
