import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const service = await readFile('src/main/browser/browser-service.ts', 'utf8')
const handlers = await readFile('src/main/ipc/browser-handlers.ts', 'utf8')
const panel = await readFile('src/renderer/src/components/layout/BrowserPanel.tsx', 'utf8')
const tools = await readFile('src/renderer/src/lib/tools/browser-native-ui.ts', 'utf8')
const channels = await readFile('src/shared/ipc/contract.ts', 'utf8')
const packageJson = await readFile('package.json', 'utf8')

assert.match(service, /class MainBrowserService/)
assert.match(service, /guest\.getType\(\) !== 'webview'/)
assert.match(service, /guest\.hostWebContents\?\.id !== host\.id/)
assert.match(service, /BrowserOwnershipRegistry/)
assert.match(service, /guest\.once\('destroyed'/)
assert.match(service, /host\.once\('destroyed'/)
assert.match(service, /removeHostTabs\(host\.id\)/)
assert.match(service, /tabIdByGuestWebContentsId/)
assert.match(handlers, /registerBrowserUserTab/)
assert.match(handlers, /unregisterBrowserUserTab/)
assert.match(handlers, /Browser session workspace mismatch/)
assert.match(handlers, /Browser project workspace mismatch/)
assert.match(panel, /IPC\.BROWSER_REGISTER_TAB/)
assert.match(panel, /IPC\.BROWSER_UNREGISTER_TAB/)
assert.match(tools, /BROWSER_TAKE_GUEST_RUN_CONTROL/)
assert.match(tools, /ctx\.agentRunId/)
assert.match(tools, /BROWSER_CAPTURE_PAGE/)
assert.match(tools, /BROWSER_EXECUTE_SCRIPT/)
assert.match(tools, /BROWSER_NAVIGATE_GUEST/)
assert.match(channels, /BROWSER_REGISTER_TAB/)
assert.match(channels, /BROWSER_UNREGISTER_TAB/)
assert.match(packageJson, /"verify:main-browser-service"/)

console.log('main browser service verification passed')
