import assert from 'node:assert/strict'
import fs from 'node:fs'
const tool = fs.readFileSync('src/renderer/src/lib/tools/canvas-tool.ts', 'utf8')
const registry = fs.readFileSync('src/renderer/src/lib/tools/index.ts', 'utf8')
const store = fs.readFileSync('src/renderer/src/stores/draw-graph-store.ts', 'utf8')
const canvas = fs.readFileSync('src/renderer/src/components/draw/DrawGraphCanvas.tsx', 'utf8')
const english = fs.readFileSync('src/renderer/src/locales/en/layout.json', 'utf8')
assert.match(tool, /name: 'CanvasOperation'/)
assert.match(tool, /requiresApproval: \(input\) => input.action !== 'inspect'/)
assert.match(registry, /updateCanvasToolRegistration/)
assert.match(registry, /advancedDrawEnabled/)
assert.match(registry, /unregisterCanvasTool/)
assert.doesNotMatch(tool, /draw-graph:save/)
assert.match(tool, /useDrawGraphStore/)
assert.match(store, /changes:/)
assert.match(store, /source: 'assistant'/)
assert.match(store, /await ipcClient\.invoke\('draw-graph:save', project\)/)
for (const action of ['update_node', 'delete_nodes', 'disconnect']) {
  assert.match(tool, new RegExp(`'${action}'`))
  assert.match(store, new RegExp(`action === '${action}'`))
}
assert.match(store, /wouldCreateDrawGraphCycle/)
assert.match(store, /acquireAssistantMutation/)
assert.match(store, /await persist\(next\)\s+set\(\{ project: next \}\)/)
assert.match(canvas, /openCanvasAssistant/)
assert.match(canvas, /getSessionInputDraftKey\(sessionId\)/)
assert.match(canvas, /navigateToSession\(sessionId\)/)
assert.match(english, /use only CanvasOperation for canvas mutations/)
console.log('Draw canvas assistant verification passed')
