export type {
  OlaDeviceConnectionConfig,
  RdpConnectionConfig,
  RemoteConnection,
  RemoteConnectionCreateInput,
  RemoteConnectionCreateRequest,
  RemoteConnectionKind,
  RemoteConnectInput,
  RemoteConnectResult,
  RemoteCredentialClaimRequest,
  RemoteConnectionListResult,
  RemoteConnectionTestResult,
  RemoteConnectionUpdateInput,
  RemoteConnectionUpdateRequest,
  RemoteSession,
  RemoteViewerCredential,
  RemoteInputEnvelope,
  RemoteInputEvent,
  VncConnectionConfig
} from '../../../../shared/remote-control'
